"""Generate the settings reference from declared defaults, schema and validator source."""

import argparse
import ast
import inspect
import json
import textwrap
from pathlib import Path

from pydantic import SecretStr
from voice_delegate.config import Settings

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/configuration.md"


def validator_source() -> str:
    source = inspect.getsource(Settings)
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == "validate_production":
            return textwrap.dedent(
                "\n".join(source.splitlines()[node.lineno - 2 : node.end_lineno])
            )
    message = "Settings validator not found"
    raise ValueError(message)


def build() -> str:
    schema = Settings.model_json_schema(by_alias=False)["properties"]
    lines = [
        "# Configuration",
        "",
        "Generated from `backend/src/voice_delegate/config.py`. Do not edit this file directly.",
        "Run `uv run python scripts/build_configuration.py`; pytest checks for drift.",
        "",
        "Settings load at process startup. Process environment overrides root `.env`; restart",
        "after changes. JSON arrays/objects are required for hosts and invitation mappings.",
        "Declared defaults below never read your environment or reveal configured secrets.",
        "",
        "| Field | Environment variable | Default | Field validation |",
        "|---|---|---|---|",
    ]
    constraint_keys = (
        "type",
        "enum",
        "minimum",
        "maximum",
        "exclusiveMinimum",
        "exclusiveMaximum",
        "pattern",
    )
    for name, field in Settings.model_fields.items():
        env = field.validation_alias or "VOICE_" + name.upper()
        default = field.get_default(call_default_factory=True)
        if isinstance(default, SecretStr):
            default = default.get_secret_value()
        constraints = {key: schema[name][key] for key in constraint_keys if key in schema[name]}
        lines.append(
            f"| `{name}` | `{env}` | `{json.dumps(default)}` | `{json.dumps(constraints)}` |"
        )
    lines += [
        "",
        "## Cross-field validator rules",
        "",
        "Every configuration is also checked by the exact validator below. This includes",
        "production HTTPS and host restrictions, invitation length/uniqueness, durable",
        "public-demo quotas, Azure origins, remote-worker credentials and provider choices.",
        "The code is generated verbatim so changes to any validator fail the drift test.",
        "Field types use Pydantic's normal environment parsing; this is not strict JSON typing.",
        "",
        "```python",
        validator_source(),
        "```",
        "",
        "## Hosting configuration",
        "",
        "Vercel serves the static frontend: set only `VITE_API_BASE_URL` to the backend HTTPS",
        "origin. It is public build-time configuration and requires a new frontend build.",
        "Set `OPENAI_API_KEY` and applicable `VOICE_*` settings on Railway or Render, never",
        "in browser-prefixed variables. Keep provider keys, invitation and worker tokens private.",
        "Railway-specific variables such as `RAILWAY_DOCKERFILE_PATH` and `RAILWAY_RUN_UID`",
        "belong to the hosting platform, not Settings. See [deployment](../deployment/README.md).",
        "",
        "Quota meanings and incident procedures: [operations](operations.md).",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = build()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != rendered:
            message = "Configuration documentation has drifted; run scripts/build_configuration.py"
            raise SystemExit(message)
    else:
        OUTPUT.write_text(rendered)


if __name__ == "__main__":
    main()
